language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"

# command to install dependencies
install:
  - pip install pytest coverage pytest-cov codecov
  - pip install .

# command to run tests
script:
  - coverage run -m pytest

after_success:
  - codecov
